# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c725c84084dc1094fe28154a0e35f0c3bf2ff6b05c71c26788c88f1d856ca91322aea348252865d2a5d773c2aeef4314a302f78d9c5d8030a4dae14960dcda

test:
  secret_key_base: 769bfaf643c1a6044cc86c4e3b406ff8494eca48dff702a65daaec4ff4da553c7a817b4b862b2a9ee623160f843812613e0a1ab36aef02c259ab6e1a5539c844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
